[context.production]
command = "yarn generate-deploy && next build"
publish = ".next"
[context.production.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://bewgymyresxixvkkqbzl.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "bewgymyresxixvkkqbzl"
NEXT_PUBLIC_SITE_URL = 'https://conject.io'
NEXT_PUBLIC_CONTEXT = "prod"
NEXT_PUBLIC_LANGFUSE_HOST="https://cloud.langfuse.com"



[functions]
  directory = "netlify/functions"

[context.branch-deploy]
command = "yarn generate-deploy && next build"
publish = ".next"
[context.branch-deploy.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://bewgymyresxixvkkqbzl.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "bewgymyresxixvkkqbzl"
NEXT_PUBLIC_SITE_URL = 'https://conject.io'
NEXT_PUBLIC_CONTEXT = "branch-deploy"
NEXT_PUBLIC_LANGFUSE_HOST="https://cloud.langfuse.com"

[context.development]
command = "yarn generate && next build"
publish = ".next"
[context.development.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://bewgymyresxixvkkqbzl.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "bewgymyresxixvkkqbzl"
NEXT_PUBLIC_SITE_URL = 'https://conject.io'
NEXT_PUBLIC_CONTEXT = "development"
NEXT_PUBLIC_LANGFUSE_HOST="https://cloud.langfuse.com"

[dev]
command = "next dev"
port = 8888
targetPort = 3000
context = "dev"


# [[redirects]]
#   from = "https://conject.io/posts/*"
#   to = "https://conject.io/posts/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://conject.io/explore/*"
#   to = "https://conject.io/explore/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://conject.io/join/*"
#   to = "https://conject.io/join/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://conject.io/feed"
#   to = "https://conject.io/feed"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://conject.io/statements/*"
#   to = "https://conject.io/statements/:splat"
#   status = 301
#   force = true