revoke delete on table "public"."statement_url" from "anon";

revoke insert on table "public"."statement_url" from "anon";

revoke references on table "public"."statement_url" from "anon";

revoke select on table "public"."statement_url" from "anon";

revoke trigger on table "public"."statement_url" from "anon";

revoke truncate on table "public"."statement_url" from "anon";

revoke update on table "public"."statement_url" from "anon";

revoke delete on table "public"."statement_url" from "authenticated";

revoke insert on table "public"."statement_url" from "authenticated";

revoke references on table "public"."statement_url" from "authenticated";

revoke select on table "public"."statement_url" from "authenticated";

revoke trigger on table "public"."statement_url" from "authenticated";

revoke truncate on table "public"."statement_url" from "authenticated";

revoke update on table "public"."statement_url" from "authenticated";

revoke delete on table "public"."statement_url" from "service_role";

revoke insert on table "public"."statement_url" from "service_role";

revoke references on table "public"."statement_url" from "service_role";

revoke select on table "public"."statement_url" from "service_role";

revoke trigger on table "public"."statement_url" from "service_role";

revoke truncate on table "public"."statement_url" from "service_role";

revoke update on table "public"."statement_url" from "service_role";

alter table "public"."statement_image" drop constraint "statement_image_creator_id_fkey";

alter table "public"."statement_url" drop constraint "statement_url_statement_id_key";

alter table "public"."statement_url" drop constraint "statement_url_pkey";

drop index if exists "public"."statement_url_pkey";

drop index if exists "public"."statement_url_statement_id_key";

drop table "public"."statement_url";

create table "public"."collaborator" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "statement_id" text not null,
    "user_id" uuid not null,
    "role" text not null
);


alter table "public"."collaborator" enable row level security;

create table "public"."statement" (
    "slug" text not null,
    "statement_id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "parent_statement_id" text
);


alter table "public"."statement" enable row level security;

alter table "public"."draft" drop column "parent_statement_id";

alter table "public"."statement_image" drop column "creator_id";


CREATE UNIQUE INDEX statement_pkey1 ON public.statement USING btree (statement_id);

CREATE UNIQUE INDEX statement_slug_key ON public.statement USING btree (slug);

CREATE UNIQUE INDEX statement_url_statement_id_key ON public.statement USING btree (statement_id);

alter table "public"."statement" add constraint "statement_pkey1" PRIMARY KEY using index "statement_pkey1";

alter table "public"."collaborator" add constraint "collaborator_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(id) ON DELETE CASCADE not valid;

alter table "public"."collaborator" validate constraint "collaborator_user_id_fkey";

alter table "public"."collaborator" add constraint "collaborator_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statement(statement_id) ON DELETE CASCADE not valid;

alter table "public"."collaborator" validate constraint "collaborator_statement_id_fkey";

alter table "public"."draft" add constraint "draft_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statement(statement_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."draft" validate constraint "draft_statement_id_fkey";

alter table "public"."statement" add constraint "statement_parent_statement_id_fkey" FOREIGN KEY (parent_statement_id) REFERENCES statement(statement_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."statement" validate constraint "statement_parent_statement_id_fkey";

alter table "public"."statement" add constraint "statement_slug_key" UNIQUE using index "statement_slug_key";

alter table "public"."statement" add constraint "statement_url_statement_id_key" UNIQUE using index "statement_url_statement_id_key";

alter table "public"."statement_citation" add constraint "statement_citation_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statement(statement_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."statement_citation" validate constraint "statement_citation_statement_id_fkey";

alter table "public"."statement_image" add constraint "statement_image_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statement(statement_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."statement_image" validate constraint "statement_image_statement_id_fkey";

alter table "public"."statement_vote" add constraint "statement_vote_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statement(statement_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."statement_vote" validate constraint "statement_vote_statement_id_fkey";

grant delete on table "public"."collaborator" to "anon";

grant insert on table "public"."collaborator" to "anon";

grant references on table "public"."collaborator" to "anon";

grant select on table "public"."collaborator" to "anon";

grant trigger on table "public"."collaborator" to "anon";

grant truncate on table "public"."collaborator" to "anon";

grant update on table "public"."collaborator" to "anon";

grant delete on table "public"."collaborator" to "authenticated";

grant insert on table "public"."collaborator" to "authenticated";

grant references on table "public"."collaborator" to "authenticated";

grant select on table "public"."collaborator" to "authenticated";

grant trigger on table "public"."collaborator" to "authenticated";

grant truncate on table "public"."collaborator" to "authenticated";

grant update on table "public"."collaborator" to "authenticated";

grant delete on table "public"."collaborator" to "service_role";

grant insert on table "public"."collaborator" to "service_role";

grant references on table "public"."collaborator" to "service_role";

grant select on table "public"."collaborator" to "service_role";

grant trigger on table "public"."collaborator" to "service_role";

grant truncate on table "public"."collaborator" to "service_role";

grant update on table "public"."collaborator" to "service_role";

grant delete on table "public"."statement" to "anon";

grant insert on table "public"."statement" to "anon";

grant references on table "public"."statement" to "anon";

grant select on table "public"."statement" to "anon";

grant trigger on table "public"."statement" to "anon";

grant truncate on table "public"."statement" to "anon";

grant update on table "public"."statement" to "anon";

grant delete on table "public"."statement" to "authenticated";

grant insert on table "public"."statement" to "authenticated";

grant references on table "public"."statement" to "authenticated";

grant select on table "public"."statement" to "authenticated";

grant trigger on table "public"."statement" to "authenticated";

grant truncate on table "public"."statement" to "authenticated";

grant update on table "public"."statement" to "authenticated";

grant delete on table "public"."statement" to "service_role";

grant insert on table "public"."statement" to "service_role";

grant references on table "public"."statement" to "service_role";

grant select on table "public"."statement" to "service_role";

grant trigger on table "public"."statement" to "service_role";

grant truncate on table "public"."statement" to "service_role";

grant update on table "public"."statement" to "service_role";


