create table "public"."subscription" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "recipient_id" uuid,
    "author_id" uuid,
    "medium" text default 'email'::text,
    "handle" text,
    "paused" boolean default false
);


alter table "public"."subscription" enable row level security;

CREATE UNIQUE INDEX subscription_pkey ON public.subscription USING btree (id);

CREATE UNIQUE INDEX subscription_unique_combo ON public.subscription USING btree (recipient_id, author_id, handle);

alter table "public"."subscription" add constraint "subscription_pkey" PRIMARY KEY using index "subscription_pkey";

alter table "public"."subscription" add constraint "subscription_author_id_fkey" FOREIGN KEY (author_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subscription" validate constraint "subscription_author_id_fkey";

alter table "public"."subscription" add constraint "subscription_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subscription" validate constraint "subscription_recipient_id_fkey";

alter table "public"."subscription" add constraint "subscription_unique_combo" UNIQUE using index "subscription_unique_combo";

grant delete on table "public"."subscription" to "anon";

grant insert on table "public"."subscription" to "anon";

grant references on table "public"."subscription" to "anon";

grant select on table "public"."subscription" to "anon";

grant trigger on table "public"."subscription" to "anon";

grant truncate on table "public"."subscription" to "anon";

grant update on table "public"."subscription" to "anon";

grant delete on table "public"."subscription" to "authenticated";

grant insert on table "public"."subscription" to "authenticated";

grant references on table "public"."subscription" to "authenticated";

grant select on table "public"."subscription" to "authenticated";

grant trigger on table "public"."subscription" to "authenticated";

grant truncate on table "public"."subscription" to "authenticated";

grant update on table "public"."subscription" to "authenticated";

grant delete on table "public"."subscription" to "service_role";

grant insert on table "public"."subscription" to "service_role";

grant references on table "public"."subscription" to "service_role";

grant select on table "public"."subscription" to "service_role";

grant trigger on table "public"."subscription" to "service_role";

grant truncate on table "public"."subscription" to "service_role";

grant update on table "public"."subscription" to "service_role";


