create table "public"."notification_policy" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "handle" text not null,
    "medium" text not null,
    "recipient_id" uuid not null,
    "object_id" text not null,
    "paused" boolean not null default false
);


alter table "public"."notification_policy" enable row level security;

CREATE UNIQUE INDEX notification_policy_pkey ON public.notification_policy USING btree (id);

alter table "public"."notification_policy" add constraint "notification_policy_pkey" PRIMARY KEY using index "notification_policy_pkey";

alter table "public"."notification_policy" add constraint "notification_policy_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notification_policy" validate constraint "notification_policy_recipient_id_fkey";

grant delete on table "public"."notification_policy" to "anon";

grant insert on table "public"."notification_policy" to "anon";

grant references on table "public"."notification_policy" to "anon";

grant select on table "public"."notification_policy" to "anon";

grant trigger on table "public"."notification_policy" to "anon";

grant truncate on table "public"."notification_policy" to "anon";

grant update on table "public"."notification_policy" to "anon";

grant delete on table "public"."notification_policy" to "authenticated";

grant insert on table "public"."notification_policy" to "authenticated";

grant references on table "public"."notification_policy" to "authenticated";

grant select on table "public"."notification_policy" to "authenticated";

grant trigger on table "public"."notification_policy" to "authenticated";

grant truncate on table "public"."notification_policy" to "authenticated";

grant update on table "public"."notification_policy" to "authenticated";

grant delete on table "public"."notification_policy" to "service_role";

grant insert on table "public"."notification_policy" to "service_role";

grant references on table "public"."notification_policy" to "service_role";

grant select on table "public"."notification_policy" to "service_role";

grant trigger on table "public"."notification_policy" to "service_role";

grant truncate on table "public"."notification_policy" to "service_role";

grant update on table "public"."notification_policy" to "service_role";


