slug: seed-data-changes
name: seed-data-changes
description: Use this skill to make changes to the seed data.
tags: []
compat: []
sha256: 705dea89c898c4d57902d09fe37eb31df7ee48dd73690e5da84cdd3bbe2d190e
